//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_product = new HashSet<order_product>();
            this.order_agent = new HashSet<order_agent>();
        }
    
        public int id { get; set; }
        public string order_name { get; set; }
        public string deliver_to { get; set; }
        public string deliver_date { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<order_product> order_product { get; set; }
        public virtual ICollection<order_agent> order_agent { get; set; }
    }
}
